### ISSUE TITLE
Improve export/import

### ISSUE THREAD

**Issue by wybiral** [wybiral/quantum#6]
This shouldn't rely on the user pasting in JSON. There should be an actual file import.

**Comment by Strilanc** [comment]
We should consider making Quirk and this simulator (name?) having common JSON exports so they can interop.

Although I'm not quite sure if it could be done... we have inconsistent feature sets (e.g. Quirk's controls can't apply to a single gate out of a column).

**Comment by wybiral** [comment]
That's a great idea. At the least it may help for us to add some kind of identifier. My plan is to add a ```version``` property but it would make sense to also add something to identify which app it came from.

Formalizing a set of features and sharing a format would be awesome but you're right about there being compatibility issues. We need to agree on a subset and find a way to handle outlying features. I'd be interested in discussing that option further though.

As for the name... I should probably work on that (open to suggestions).

**Comment by Strilanc** [comment]
Hmmm. This might be too tricky to get right.

Presumably there would be a way to describe a gate in terms of its matrix or else in terms of a circuit. But Quirk has concepts that don't quite fit into the "gate" concept, like the "input A" gate that pairs with "+=A"/"-=A","+=AB" gates in the same column. If the description format didn't have the concept of gates with independently moveable pieces, every relative positioning of the two pieces would have to be described separately. Not to mention situations where one input is feeding two arithmetic gates in the same column.

Another possible issue is that some operations are way *way* more efficiently described by code than a matrix or a circuit. For example, Quirk's implementation of the increment gate basically amounts to `return mod(out_id + 1, span);`. Specifying that as a matrix, even with a sparse representation, would have exponential overhead in the span of the gate. Specifying it as a circuit has quadratic overhead (well... there are linear sized circuits for incrementing, but it would be quite a lot of overkill to do it that way and the constant factor on the size kind of sucks).

**Comment by wybiral** [comment]
This simulator only supports basic unitary operators (the most common ones I could find in papers) and there is no way to use arbitrary matrices or code at this point. Everything is composed from those (either directly or by compiling circuits to create user defined ones).

But, if there was a way to detect that it was dealing with an export from your simulator it could just warn that some features aren't supported but still load circuits such as:

```
{
  "cols": [
    [
      "H"
    ],
    [
      "•",
      "X"
    ]
  ]
}
```

**Comment by wybiral** [comment]
https://github.com/wybiral/quantum/commit/64475d92d30f04fcaad9a626b6311bcad9a8e546
